name: Deploy

on:
  workflow_run:
    workflows: [Tests]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    name: Publish new crate version
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/run_cargo.yaml
    with:
      cargo-command: cargo publish