name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    name: Run all tests
    uses: ./.github/workflows/run_cargo.yaml
    with:
      cargo-command: cargo test --verbose
  deploy:
    name: Publish new crate version
    needs: run-tests
    uses: ./.github/workflows/run_cargo.yaml
    with:
      cargo-command: cargo publish
    secrets:
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}