name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  run-tests-and-deploy:
    name: Publish new crate version
    uses: ./.github/workflows/run_cargo.yaml
    with:
      cargo-command: cargo test --verbose && cargo publish
    secrets:
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}