name: Reusable workflow to prepare environment and run a cargo command

on:
  workflow_call:
    inputs:
      cargo-command:
        required: true
        type: string
    secrets:
      cargo-registry-token:
        required: false

jobs:
  run-cargo:
    name: ${{ inputs.cargo-command }}
    runs-on: ubuntu-latest
    environment: Rust Crates
    steps:
      - name: Install alsa (needed for alsa-sys crate)
        run: sudo apt-get install alsa libasound2-dev libudev-dev
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ${{ inputs.cargo-command }}
        run: ${{ inputs.cargo-command }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.cargo-registry-token }}
          CARGO_TERM_COLOR: always