name: Reusable workflow to prepare environment and run a cargo command

on:
  workflow_call:
    inputs:
      cargo-command:
        required: true
        type: string
      clean-compile:
        required: false
        type: boolean
        default: false
    secrets:
      cargo-registry-token:
        required: false

jobs:
  run-cargo:
    name: ${{ inputs.cargo-command }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if compiled sources can be downloaded
        if: ${{ inputs.clean-compile == false }}
        uses: softwareforgood/check-artifact-v4-existence@v0
        id: check-compilation-result-exists
        with:
          name: compilation-result-${{ github.sha }}
      - name: Download compiled sources
        if: ${{ steps.check-compilation-result-exists.outputs.exists == true }}
        uses: actions/download-artifact@v4
        with:
          name: compilation-result-${{ github.sha }}
          path: target
      - name: Install alsa (needed for alsa-sys crate)
        run: sudo apt-get install alsa libasound2-dev libudev-dev
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ${{ inputs.cargo-command }}
        run: ${{ inputs.cargo-command }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.cargo-registry-token }}
          CARGO_TERM_COLOR: always
      - name: Upload compiled sources
        if: ${{ steps.check-compilation-result-exists.outputs.exists == false }}
        uses: actions/upload-artifact@v4
        with:
          name: compilation-result-${{ github.sha }}
          path: target