name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  run-tests:
    name: Run all tests
    uses: ./.github/workflows/run_cargo.yaml
    with:
      cargo-command: cargo test --verbose